### PR TITLE
Fixed the background color issue. Activities card works fine now.

### PR DESCRIPTION
**Pull request by Tsumiiiiiiii**

### CODE REVIEW

**Comment by moudud99** [comment]
Problem with text color and text font. layout.jsx needs to be fixed first.

**Comment by mostafiz93** [comment]
> Problem with text color and text font. layout.jsx needs to be fixed first.

@moudud99  Could you please attach a screenshot?

**Comment by Ssshanto** [comment]
image
Activities text color becomes white (on white background) and font changes to Times New Roman, as it tries and fails to re-download Inter due to issues in layout.tsx

**Comment by Tsumiiiiiiii** [comment]
Closing the pull request. Waiting for reaz to pull first

**Pull request closed without merging**
