### PR TITLE
Added single tree search and tree details. Minor changes in aesthetics and minor bugfixes. Minor aesthetical change in ActivityImageCard component. Added error page under search.

### PR DESCRIPTION
**Pull request by moudud99**
image
image
image
image
image

### CODE REVIEW

**Comment by moudud99** [comment]
@Ssshanto please check if the font is still broken.

**Comment by mostafiz93** [comment]
In the tree details page (root/t) texts are in white color.  Please check attached screenshot (in the second one I've selected the texts with cursor to make them visible)  

image


image

**Comment by mostafiz93** [comment]
I suspect there is conflict in the tailwind class names in two components.  Check the tailwind class names with the browser's inspect element tool and if this is the case just name them differently. Let me know if that's not the case, will have to troubleshoot more. 

Keeping this PR open till the discussion is going on.

**Comment by moudud99** [comment]
@mostafiz93 I couldn't find any class conflict. However @Ssshanto fixed it through globals.css . Still working on it.

**Pull request merged**
