### PR TITLE
Responsive Navbar, Responsive section & transition effects on scrolling 

### PR DESCRIPTION
**Pull request by sanz47**
https://github.com/tree-pp/TreePP/assets/84383654/e56d3d4c-ed6f-4c07-a24b-1b0104872d7e

### CODE REVIEW

**Comment by sanz47** [comment]
image

**Comment by mostafiz93** [comment]
Thank you so much @sanz47 for huge effort! It looks really amazing! I've two observations (@tree-pp/reviewers please do participate):

- In my phone it a few sections are broken, please find the attached screenshot
-  Found that 10 new packages are installed, I was wondering if all these 10 are strictly required? 


https://github.com/tree-pp/TreePP/assets/1145582/d5f1ca39-95ef-4fdb-bcaf-b4ae0514e068

**Comment by moudud99** [comment]
@sanz47 Very nice work. Works fine on my device. The navbar menu design can be improved.
@mostafiz93 The broken sections are not responsive yet.

**Comment by sanz47** [comment]
> Thank you so much @sanz47 for huge effort! It looks really amazing! I've two observations (@tree-pp/reviewers please do participate):
> 
> * In my phone it a few sections are broken, please find the attached screenshot
> * Found that 10 new packages are installed, I was wondering if all these 10 are strictly required?
> 
>  rpreplay-final1692096091-1_dmrOzpfn.mp4

1. I've made only the first section for mobile, I thought other sections will be done if it worked. And, @Ssshanto was thinking about redesigning these sections. So, I only changed the top section. 

2. About packages, I installed many packages for scroll animation 😅 to see which worked better. not all packages are necessary.

**Pull request closed without merging**
